capAdmin_app/urls.py
from django.urls import path
from  .views import *

app_name = "capAdmin_app"


urlpatterns = [
    path('', admin_base, name='admin_base'),
    path('profile/', profile, name='profile'),
    path('profile_list/', profile_list, name='profile_list'),

]

crypto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("cap_app.urls")),
    path("admin_panel/", include("capAdmin_app.urls")),

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/admin_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Responsive Admin</title>
    <!-- ======= Styles ====== -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
</head>

<body>
    <!-- =============== Navigation ================ -->
    <div class="container">
        <div class="navigation">
            <ul>
                <li>
                    <a href="#">
                        <span class="icon">
                        </span>
                        <span class="title"><h2>CryptoBook</h2></span>
                    </a>
                </li>

                <li>
                    <a href="#">
                        <span class="icon">
                            <ion-icon name="home-outline"></ion-icon>
                        </span>
                        <span class="title">Dashboard</span>
                    </a>
                </li>

                <li>
                    <a href="#">
                        <span class="icon">
                            <ion-icon name="people-outline"></ion-icon>
                        </span>
                        <span class="title">Customers</span>
                    </a>
                </li>

                <li>
                    <a href="#">
                        <span class="icon">
                            <ion-icon name="chatbubble-outline"></ion-icon>
                        </span>
                        <span class="title">Messages</span>
                    </a>
                </li>

                <li>
                    <a href="#">
                        <span class="icon">
                            <ion-icon name="help-outline"></ion-icon>
                        </span>
                        <span class="title">Help</span>
                    </a>
                </li>

                <li>
                    <a href="#">
                        <span class="icon">
                            <ion-icon name="settings-outline"></ion-icon>
                        </span>
                        <span class="title">Settings</span>
                    </a>
                </li>


                <li>
                  <a href="{% url 'capAdmin_app:profile' %}">
                      <span class="icon">
                          <ion-icon name="lock-closed-outline"></ion-icon>
                      </span>
                      <span class="title">My Profile</span>
                  </a>
              </li>

                <li>
                    <a href="#">
                        <span class="icon">
                            <ion-icon name="log-out-outline"></ion-icon>
                        </span>
                        <span class="title">Sign Out</span>
                    </a>
                </li>
            </ul>
        </div>

        <!-- ========================= Main ==================== -->
        <div class="main">
            <div class="topbar">
                <div class="toggle">
                    <ion-icon name="menu-outline"></ion-icon>
                </div>

                <div class="search">
                    <label>
                        <input type="text" placeholder="Search here">
                        <ion-icon name="search-outline"></ion-icon>
                    </label>
                </div>

                <div class="user">
                    <img src="assets/imgs/customer01.jpg" alt="">
                </div>
            </div>

            <!-- ======================= Cards ================== -->
            <div class="cardBox">
                <div class="card">
                    <div>
                        <div class="numbers">1,504</div>
                        <div class="cardName">Daily Views</div>
                    </div>

                    <div class="iconBx">
                        <ion-icon name="eye-outline"></ion-icon>
                    </div>
                </div>

                <div class="card">
                    <div>
                        <div class="numbers">80</div>
                        <div class="cardName">Sales</div>
                    </div>

                    <div class="iconBx">
                        <ion-icon name="cart-outline"></ion-icon>
                    </div>
                </div>

                <div class="card">
                    <div>
                        <div class="numbers">284</div>
                        <div class="cardName">Comments</div>
                    </div>

                    <div class="iconBx">
                        <ion-icon name="chatbubbles-outline"></ion-icon>
                    </div>
                </div>

                <div class="card">
                    <div>
                        <div class="numbers">$7,842</div>
                        <div class="cardName">Earning</div>
                    </div>

                    <div class="iconBx">
                        <ion-icon name="cash-outline"></ion-icon>
                    </div>
                </div>
            </div>

            <!-- ================ Order Details List ================= -->
            <div class="details">
                <div class="recentOrders">
                    <div class="cardHeader">
                        <h2>Recent Orders</h2>
                        <a href="#" class="btn">View All</a>
                    </div>

                    <table>
                        <thead>
                            <tr>
                                <td>Name</td>
                                <td>Price</td>
                                <td>Payment</td>
                                <td>Status</td>
                            </tr>
                        </thead>

                        <tbody>
                            <tr>
                                <td>Star Refrigerator</td>
                                <td>$1200</td>
                                <td>Paid</td>
                                <td><span class="status delivered">Delivered</span></td>
                            </tr>

                            <tr>
                                <td>Dell Laptop</td>
                                <td>$110</td>
                                <td>Due</td>
                                <td><span class="status pending">Pending</span></td>
                            </tr>

                            <tr>
                                <td>Apple Watch</td>
                                <td>$1200</td>
                                <td>Paid</td>
                                <td><span class="status return">Return</span></td>
                            </tr>

                            <tr>
                                <td>Addidas Shoes</td>
                                <td>$620</td>
                                <td>Due</td>
                                <td><span class="status inProgress">In Progress</span></td>
                            </tr>

                            <tr>
                                <td>Star Refrigerator</td>
                                <td>$1200</td>
                                <td>Paid</td>
                                <td><span class="status delivered">Delivered</span></td>
                            </tr>

                            <tr>
                                <td>Dell Laptop</td>
                                <td>$110</td>
                                <td>Due</td>
                                <td><span class="status pending">Pending</span></td>
                            </tr>

                            <tr>
                                <td>Apple Watch</td>
                                <td>$1200</td>
                                <td>Paid</td>
                                <td><span class="status return">Return</span></td>
                            </tr>

                            <tr>
                                <td>Addidas Shoes</td>
                                <td>$620</td>
                                <td>Due</td>
                                <td><span class="status inProgress">In Progress</span></td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <!-- ================= New Customers ================ -->
                <div class="recentCustomers">
                    <div class="cardHeader">
                        <h2>Recent Customers</h2>
                    </div>

                    <table>
                        <tr>
                            <td width="60px">
                                <div class="imgBx"><img src="assets/imgs/customer02.jpg" alt=""></div>
                            </td>
                            <td>
                                <h4>David <br> <span>Italy</span></h4>
                            </td>
                        </tr>

                        <tr>
                            <td width="60px">
                                <div class="imgBx"><img src="assets/imgs/customer01.jpg" alt=""></div>
                            </td>
                            <td>
                                <h4>Amit <br> <span>India</span></h4>
                            </td>
                        </tr>

                        <tr>
                            <td width="60px">
                                <div class="imgBx"><img src="assets/imgs/customer02.jpg" alt=""></div>
                            </td>
                            <td>
                                <h4>David <br> <span>Italy</span></h4>
                            </td>
                        </tr>

                        <tr>
                            <td width="60px">
                                <div class="imgBx"><img src="assets/imgs/customer01.jpg" alt=""></div>
                            </td>
                            <td>
                                <h4>Amit <br> <span>India</span></h4>
                            </td>
                        </tr>

                        <tr>
                            <td width="60px">
                                <div class="imgBx"><img src="assets/imgs/customer02.jpg" alt=""></div>
                            </td>
                            <td>
                                <h4>David <br> <span>Italy</span></h4>
                            </td>
                        </tr>

                        <tr>
                            <td width="60px">
                                <div class="imgBx"><img src="assets/imgs/customer01.jpg" alt=""></div>
                            </td>
                            <td>
                                <h4>Amit <br> <span>India</span></h4>
                            </td>
                        </tr>

                        <tr>
                            <td width="60px">
                                <div class="imgBx"><img src="assets/imgs/customer01.jpg" alt=""></div>
                            </td>
                            <td>
                                <h4>David <br> <span>Italy</span></h4>
                            </td>
                        </tr>

                        <tr>
                            <td width="60px">
                                <div class="imgBx"><img src="assets/imgs/customer02.jpg" alt=""></div>
                            </td>
                            <td>
                                <h4>Amit <br> <span>India</span></h4>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <!-- =========== Scripts =========  -->
    <script src="{% static 'assets/js/main.js' %}"></script>

    <!-- ====== ionicons ======= -->
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</body>

</html>

templates/admin_index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Responsive Admin</title>
    <!-- ======= Styles ====== -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'admin_assets/css/myprofile.css' %}">




</head>

<body>
    <!-- =============== Navigation ================ -->
    <div class="container">
        <div class="navigation">
            <ul>
                <li>
                    <a href="#">
                        <span class="icon">
                        </span>
                        <span class="title"><h2>CryptoBook</h2></span>
                    </a>
                </li>

                <li>
                    <a href="#">
                        <span class="icon">
                            <ion-icon name="home-outline"></ion-icon>
                        </span>
                        <span class="title">Dashboard</span>
                    </a>
                </li>

                <li>
                    <a href="#">
                        <span class="icon">
                            <ion-icon name="people-outline"></ion-icon>
                        </span>
                        <span class="title">Customers</span>
                    </a>
                </li>

                <li>
                    <a href="#">
                        <span class="icon">
                            <ion-icon name="chatbubble-outline"></ion-icon>
                        </span>
                        <span class="title">Messages</span>
                    </a>
                </li>

                <li>
                    <a href="#">
                        <span class="icon">
                            <ion-icon name="help-outline"></ion-icon>
                        </span>
                        <span class="title">Help</span>
                    </a>
                </li>

                <li>
                    <a href="#">
                        <span class="icon">
                            <ion-icon name="settings-outline"></ion-icon>
                        </span>
                        <span class="title">Settings</span>
                    </a>
                </li>


                <li>
                  <a href="{% url 'capAdmin_app:profile' %}">
                      <span class="icon">
                          <ion-icon name="lock-closed-outline"></ion-icon>
                      </span>
                      <span class="title">My Profile</span>
                  </a>
              </li>

                <li>
                    <a href="#">
                        <span class="icon">
                            <ion-icon name="log-out-outline"></ion-icon>
                        </span>
                        <span class="title">Sign Out</span>
                    </a>
                </li>
            </ul>
        </div>

        <!-- ========================= Main ==================== -->
        <div class="main">
            <div class="topbar">
                <div class="toggle">
                    <ion-icon name="menu-outline"></ion-icon>
                </div>

                <div class="search">
                    <label>
                        <input type="text" placeholder="Search here">
                        <ion-icon name="search-outline"></ion-icon>
                    </label>
                </div>

                <div class="user">
                    <img src="assets/imgs/customer01.jpg" alt="">
                </div>
            </div>

            <!-- ======================= content block ================== -->
            <div id="content">
                {% block content %}
                
                
                {% endblock %}
            </div>

    <!-- =========== Scripts =========  -->
    <script src="{% static 'assets/js/main.js' %}"></script>

    <!-- ====== ionicons ======= -->
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</body>

</html>

templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CryptoSignaL</title>

    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/home.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap" rel="stylesheet">
    
    
<!-- #javascript for the crypto-table and live-table -->

</head>
<body>
    <body style="margin: 0;
     font-family: Arial, sans-serif; 
     background-image: url('{% static 'assets/imgs/background.jpg' %}'); 
     background-size: cover; 
     background-position: center; 
     margin-bottom: 200px;">
    
    <nav>
        <div class="logo">
            <img src="{% static 'assets/imgs/logo.png' %}" alt="CryptoSignaL Logo" width="40">
        </div>
        <a href="{% url 'home' %}" class="navbar-brand">CryptoSignaL</a>

        <ul class="navbar-options">
            <li><a href="{% url 'market_data' %}">Market</a></li>
            <li><a href="{% url 'trade' %}">Trade</a></li>
            <li><a href="{% url 'crypto_list' %}">Cryptocurrency</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'contact' %}">Contact</a></li>
        </ul>

        {% if user.is_authenticated %}
        <!-- If the user is authenticated, show the logout button -->
        <div class="login-signup">
            <div class="login">
                <a href="{% url 'user_logout' %}">Logout</a>
            </div>
        </div>
    {% else %}
        <!-- If the user is not authenticated, show the login and signup buttons -->
        <div class="login-signup">
            <div class="login">
                <a href="{% url 'user_login' %}">Login</a>
            </div>
            <a href="{% url 'user_signup' %}" class="signup-button">Signup</a>
        </div>
    {% endif %}
    </nav>






    <!-- Your webpage content goes here -->
    <h1>Trade Your Crypto</h1>
    <h1>on <span style="color: yellow;">CryptoSignaL</span></h1>
    <h1>without worries</h1>
    <p>Signup & explore your trading partner</p>
    <p><a href="{% url 'user_signup' %}" class="signup-button">Signup</a></p>




    <!-- Live text and animated GIF container -->
    <div class="live-text-container">
        <div class="live-text"><h3>Power Of Crypto</h3></div>
        <!-- Replace the placeholder with your actual animated GIF -->
        <img src="{% static 'assets/imgs/bitcoin1.gif' %}" alt="Live Animation" class="live-gif">
    </div>

    <div id="crypto-table">
        <!-- Table will be added here -->
      </div>

      <script src="{% static 'assets/js/home.js' %}"></script>


      <!-- Add this at the end of your HTML file -->
      <footer>
        <div class="footer-text">
            <p>&copy; 2024 CryptoSignaL. All Rights Reserved.</p>
            <div class="quick-links"> 
                <a href="#">Trade</a> 
                <a href="#">Market</a> 
                <a href="#">Crypto Currency</a> 
                <a href="#">Company</a> 
                <a href="#">Home</a> 
                <a href="#">About</a> 
                <a href="#">Contact</a> 
                <a href="#">Legal</a> 
                <a href="#">Trade Policy</a> 
                <a href="#">Terms of Service</a> 
                <a href="#">Privacy Policy</a> 
            </div> 
        </div>
    </footer>

</body>

</html>

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CryptoSignaL</title>

    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/index.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/market_data.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/about.css' %}">


    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
    <link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css'>
    <link rel='stylesheet' href='https://fonts.googleapis.com/css2?family=Pacifico&amp;family=Quicksand&amp;display=swap'><link rel="stylesheet" href="{% static 'assets/css/contact.css' %}">    
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap" rel="stylesheet">


   
   


</head>
<body style="margin: 0;
     font-family: Arial, sans-serif; 
     background-image: url('{% static 'assets/imgs/background.jpg' %}'); 
     background-size: cover; 
     background-position: center; 
     margin-bottom: 200px;">

    <nav>
        <div class="logo">
            <img src="{% static 'assets/imgs/logo.png' %}" alt="CryptoSignaL Logo" width="40">
        </div>
        <a href="{% url 'home' %}" class="navbar-brand">CryptoSignaL</a>

        <ul class="navbar-options">
            <li><a href="{% url 'market_data' %}">Market</a></li>
            <li><a href="{% url 'trade' %}">Trade</a></li>
            <li><a href="{% url 'crypto_list' %}">Cryptocurrency</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'contact' %}">Contact</a></li>
        </ul>

        {% if user.is_authenticated %}
        <!-- If the user is authenticated, show the logout button -->
        <div class="login-signup">
            <div class="login">
                <a href="{% url 'user_logout' %}">Logout</a>
            </div>
        </div>
    {% else %}
        <!-- If the user is not authenticated, show the login and signup buttons -->
        <div class="login-signup">
            <div class="login">
                <a href="{% url 'user_login' %}">Login</a>
            </div>
            <a href="{% url 'user_signup' %}" class="signup-button">Signup</a>
        </div>
    {% endif %}
    </nav>


    <div id="content">
        {% block content %}
        
        
        {% endblock %}
    </div>






    <footer>
        <div class="footer-text">
            <p>&copy; 2024 CryptoSignaL. All Rights Reserved.</p>
            <div class="quick-links"> 
                <a href="#">Trade</a> 
                <a href="#">Market</a> 
                <a href="#">Cryptocurrency</a> 
                <a href="#">Company</a> 
                <a href="#">Home</a> 
                <a href="#">About</a> 
                <a href="#">Contact</a> 
                <a href="#">Legal</a> 
                <a href="#">Trade Policy</a> 
                <a href="#">Terms of Service</a> 
                <a href="#">Privacy Policy</a> 
            </div> 
        </div>
    </footer>


 <!-- #javascript for the crypto-table and live-table -->
    <script
    type="module"
    src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"
  ></script>
  <script
  nomodule
  src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"
></script>
  <script src="{% static 'assets/js/about.js' %}"></script>
  <script src='https://code.jquery.com/jquery-3.3.1.slim.min.js'></script>
  <script src='https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js'></script>
  <script src='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js'></script>
  <script src='https://unpkg.com/feather-icons'></script><script  src="{% static 'assets/js/contact.js' %}"></script>
</body>
</html>

templates/user_home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CryptoSignaL</title>

    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/home.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap" rel="stylesheet">
    
    
<!-- #javascript for the crypto-table and live-table -->

</head>
<body>
    <body style="margin: 0;
     font-family: Arial, sans-serif; 
     background-image: url('{% static 'assets/imgs/background.jpg' %}'); 
     background-size: cover; 
     background-position: center; 
     margin-bottom: 200px;">
    
    <nav>
        <div class="logo">
            <img src="{% static 'assets/imgs/logo.png' %}" alt="CryptoSignaL Logo" width="40">
        </div>
        <a href="{% url 'home' %}" class="navbar-brand">CryptoSignaL</a>

        <ul class="navbar-options">
            <li><a href="{% url 'market_data' %}">Market</a></li>
            <li><a href="{% url 'trade' %}">Trade</a></li>
            <li><a href="{% url 'crypto_list' %}">Cryptocurrency</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'contact' %}">Contact</a></li>
        </ul>

        {% if user.is_authenticated %}
        <!-- If the user is authenticated, show the logout button -->
        <div class="login-signup">
            <div class="login">
                <a href="{% url 'user_logout' %}">Logout</a>
            </div>
        </div>
    {% else %}
        <!-- If the user is not authenticated, show the login and signup buttons -->
        <div class="login-signup">
            <div class="login">
                <a href="{% url 'user_login' %}">Login</a>
            </div>
            <a href="{% url 'user_signup' %}" class="signup-button">Signup</a>
        </div>
    {% endif %}
    </nav>






    <!-- Your webpage content goes here -->
    <h1>Trade Your Crypto</h1>
    <h1>on <span style="color: yellow;">CryptoSignaL</span></h1>
    <h1>without worries</h1>
    <p>Signup & explore your trading partner</p>
    <p><a href="{% url 'user_signup' %}" class="signup-button">Signup</a></p>




    <!-- Live text and animated GIF container -->
    <div class="live-text-container">
        <div class="live-text"><h3>Power Of Crypto</h3></div>
        <!-- Replace the placeholder with your actual animated GIF -->
        <img src="{% static 'assets/imgs/bitcoin1.gif' %}" alt="Live Animation" class="live-gif">
    </div>

    <div id="crypto-table">
        <!-- Table will be added here -->
      </div>

      <script src="{% static 'assets/js/home.js' %}"></script>


      <!-- Add this at the end of your HTML file -->
      <footer>
        <div class="footer-text">
            <p>&copy; 2024 CryptoSignaL. All Rights Reserved.</p>
            <div class="quick-links"> 
                <a href="#">Trade</a> 
                <a href="#">Market</a> 
                <a href="#">Crypto Currency</a> 
                <a href="#">Company</a> 
                <a href="#">Home</a> 
                <a href="#">About</a> 
                <a href="#">Contact</a> 
                <a href="#">Legal</a> 
                <a href="#">Trade Policy</a> 
                <a href="#">Terms of Service</a> 
                <a href="#">Privacy Policy</a> 
            </div> 
        </div>
    </footer>

</body>

</html>